container: clean 
	#g++ -I include/ container.cc -o container 
	g++ container.cc -o container
	g++ container_child.cc -o container_child
	g++ container_child_2.cc -o container_child_2
clean: 
	rm -f container
